### ISSUE TITLE
When is it worth it?

### ISSUE THREAD

**Issue by thomas-mc-work** [nextcloud/notify_push#156]
I'd like to have a metric, that support me building a basis of decision-making. I assume that there is a certain threshold when it starts to get recommended using the push service.

Furthermore, I imagine that it could be dependent on
a) the number of clients on the Nextcloud instance (total or concurrently active)
b) the amount of notification requests in relation to all other requests

I've created a small shell script prototype to determine the latter:

    file=/path/to/access.log
    # number of all requests
    r_all=$(wc -l "$file")
    # number of notification update requests
    r_not=$(grep -c "ocs/v2.php/apps/notifications/api/v2/notifications" "$file")
    
    # calculation of the ratio
    echo "$r_not / $r_all * 100" | bc -l

On my machine it gives a ratio of around 16 %. Is that much or too few? Is that related at all?

What do you think?

**Comment by alerque** [comment]
I‌ think you are comparing random numbers to random numbers.

I'm sure one of the use cases for this is to lower server load by getting notifications taken care of more efficiently. But that is''t my use case, my server keeps up fine either way.

For me the deciding case was 2 clients + 1 file + 1 notification. Using push notifications dropped the time it took the second client to notice a file update from the other client from a random-ish and altogether too long 5–30 seconds to something on the order of low digit milliseconds. The user experience of having a file sync and being able to tell the person on the phone "okay my sync is done, yours should have started" and having that be true instead of having them wait some part of a minute is what makes it worth it for me.
