### ISSUE TITLE
Multiple domain on same instance?

### ISSUE THREAD

**Issue by neocult-de** [nextcloud/notify_push#197]
It is possible to run notify_push for different instances / domains on the same server by using different ports and separate apps in each instance.

How about the scenario of more than one url in the same instance? Nextcloud may be called by more than one domain and other additions like Collabora allow several URLs for the same instance. Something like this possible by notify_push at the moment? Might that be a useful feature request?

**Comment by koelle25** [comment]
I'm also interested in the second question. We use something in the likes of cloud.example.com and example.cloud (one of the "newer" TLDs).

**Comment by arnowelzel** [comment]
Just my thoughts about "multiple domains for the same server": having multiple FQDNs for the same instance is a bad idea. Resources should always have a canonical name and you should redirect from all alternative names to the canonical one instead of allowing using Nexcloud with multiple names. I don't see any benefit of using cloud.example.com and example.cloud at the same time for one instance.

The only usecase I can imaging: you start with cloud.example.com first, then get many users subscribed to that and then decided to use example.cloud. Instead of telling the existing users to change their clients to use example.cloud you keep the old name as well. But still this sounds like a bad idea to me and as far I remember this is also not officially supported.

**Comment by neocult-de** [comment]
The use case is shared Nextcloud instances. We for example share the same Nextcloud instance for a Freelancer Network, but we have to be available via individual Domains for branding and reputation. (Sharing files, invite guests, call room).

It works for Collabora and Nextcloud support Multiple Domains actually. 

Even though for the same brand and instance I recommend and use your approach too for having a main domain and forward the others (for example after a switch of domain). Although one big reason, because notify_push doesn't support different domains.

If there is any ideas and experience I can share beyond that, that might help the further development, I am glad to elaborate.

**Comment by arnowelzel** [comment]
The main problem is, that the notification service runs on the **server** and does not know which domain is used by the **client**.

That's also one of the reasons why it is not a good idea to make a Nextcloud instance accessible with multiple domain names - the whole system is not designed for that. If it would be, then users would also have a setting to which domain they belong and when a client connects to the server, Nextcloud would know which domain was used.

**Comment by neocult-de** [comment]
I thought the domain would be decided by the account configured in the client and the first registration. If I add Useraccount A in my Nextcloud Desktop Client with a.example.org, I would be handled accordingly and if I would add the Useraccount A on b.example.org would receive them from there.

Another idea could be that notify_push.service is configured to run twice on different ports and it is reversed proxy accordingly to each domains (it works for different instances), why not the same instance too. But how would it look like internally and which challenges be there to support two services from one app. 

I would understand that this gives quite some additional challenges in there and that its not worth the effort. I would understand if this is not worth pursuing. But if so, I will gladly support it by testing now or at any time in the future.

**Comment by arnowelzel** [comment]
> I thought the domain would be decided by the account configured in the client and the first registration. 

No - domains are not stored at all. For Nextcloud it does not matter, you can even just switch the domain on your web server without any configuration change in Nextcloud at all. Of course the clients need to be aware of the new domain as well, but for Nextcloud nothing changes. I did not check the code of the push service in detail yet and don't know, when exactly the domain setting in the service is relevant - but if it is the domain the service should talk to, then using multiple domains for the instance should not be a problem at all since it is only one instance anyway. You may just give it a try to see if it works.

**Comment by icewind1991** [comment]
The url the push service is running under isn't user facing, so unless I'm missing something it should be fine to have clients use a single url for the push service even if they normally use different domains to access the nc instance.

**Comment by neocult-de** [comment]
@arnowelzel @icewind1991
You two got the right ideas. It is possible to have the push-service work for multiple domains. The domain that is set during setup will be the url used for the websocket, but it is not publicly facing.

So if we set up a Nextcloud Instance with Domain A and Domain B and afterwards setup notify_push as usual for Domain A (including the reverse proxy config for the webserver) and it works - then it works automatically for any other Domain like Domain B. The Nextcloud clients will automatically use the Websocket published via Domain A.

As Domain A  does not need to be configured and is not shown at the client side that is usually a non-issue in a shared instance anyways. 

We can test the behaviour with test_client and use it
./test_client DOMAINA user password
and we get the Push server found at wss://DOMAINA/push/ws and working as expected.

Then we test the second domain:
./test_client DOMAINB user password
and we get again the Push server found at wss://DOMAINA/push/ws and working as expected.

Which also means we don´t have to modify any settings in the push_service or add a second one and neither do we need to add more to the reverse proxy configuration of additional domains.

So it is working well and doesn´t need additional settings. Thanks for helping me and enabling me to check it in detail, Hope the discussion helps people who try it in the future.

Thanks! Solved.
