### ISSUE TITLE
Release file 'notify_push.tar.gz' is not in the latest version v0.6.0

### ISSUE THREAD

**Issue by Ami-OS** [nextcloud/notify_push#234]
Hi, I am always using `notify_push.tar.gz` before the v0.6.0 release, but in the latest release (v0.6.0) I can not find the `notify_push.tar.gz`.

What should I do?

**Comment by arnowelzel** [comment]
I just installed notify_push in a Nextcloud instance the first time yesterday. What is this file needed for? I did not miss anything.

**Comment by ryester19** [comment]
> I just installed notify_push in a Nextcloud instance the first time yesterday. What is this file needed for? I did not miss anything.

I was using it to build a custom Nextcloud Docker image with notify_push preinstalled

**Comment by arnowelzel** [comment]
I see.

But in fact you don't need that. Just compare https://github.com/nextcloud/notify_push/releases/download/v0.5.2/notify_push.tar.gz with https://github.com/nextcloud-releases/notify_push/releases/download/v0.6.0/notify_push-v0.6.0.tar.gz. The content is identical - except the versions of course.

**Comment by alerque** [comment]
As @arnowelzel hinted this project does not have an actual source build that requires a separate upload, the tar file previously attatched to build was just a re-upload of the `git archive` generated download available from the Release page anyway. Note the URL for this is adjustable, you can name the tar file whatever you want on download:

* `https://github.com/nextcloud-releases/notify_push/releases/download/v0.6.0/notify_push-0.6.0.tar.gz`
* `https://github.com/nextcloud-releases/notify_push/releases/download/v0.6.0/notify_push-0.6.0.zip`
* `https://github.com/nextcloud-releases/notify_push/releases/download/v0.6.0/notify_push.tar.gz`
* `https://github.com/nextcloud-releases/notify_push/releases/download/v0.6.0/notify_push.zip`
* `https://github.com/nextcloud-releases/notify_push/releases/download/v0.6.0/foobar.tar.gz`
* `https://github.com/nextcloud-releases/notify_push/releases/download/v0.6.0/foobar.zip`

GitHub will use `git archive` to generate a source tarball based on the filename you request.

The first form here (not quite what @arnowelzel used because I dropped the `v` prefix from inside the final tar filename) is probably the most canonical form and useful because it will extract to a directory of the same name.
